### ISSUE TITLE
événement pas dans à charger dans le dashboard

### ISSUE THREAD

**Issue by robot-athletics** [betrailrun/beath-track#10]
J'ai effacé le contenu de la F3585 et elle ne réapparait pas dans le dashboard pour le rechargement
 Report by Renauld Secretaire renauld.chapellier@diplomats.com 
 {"version":"0.0.0","name":"beathletics","buildDate":"\"2022-03-18T14:05:46.511Z\"","VERSION":"5b4ecbc","COMMITHASH":"5b4ecbc3e7883e33de30df8492cb18ecd557590b","BRANCH":"uat","LASTCOMMITDATETIME":"2022-03-18T15:05:21+01:00"}

**Comment by fwauters** [comment]
normal the limit for the events to be displayed in the dashboard is 15 days
