### ISSUE TITLE
Re-charger les perfs d'un event effacées

### ISSUE THREAD

**Issue by robot-athletics** [betrailrun/beath-track#5]
La suppression des résultats d'un event fonctionne bien.
Il faudrait que l'event correspondant réapparaisse dans le dashboard ("A Charger")
 Report by Renauld Secretaire renauld.chapellier@gmail.com 
 {"version":"0.0.0","name":"beathletics","buildDate":"\"2022-02-04T15:20:42.825Z\"","VERSION":"730ae4f","COMMITHASH":"730ae4f111d90644d9a69258ffd6e42950e46af9","BRANCH":"HEAD","LASTCOMMITDATETIME":"2022-02-04T16:16:01+01:00"}

**Comment by fwauters** [comment]
normalement déjà ok en uat
