### ISSUE TITLE
Format résultats concours

### ISSUE THREAD

**Issue by robot-athletics** [betrailrun/beath-track#6]
Les résultats des concours doivent avoir tjrs 2 chiffres derrière la virgule,
 Report by Renauld Chapellier renauld.chapellier@gmail.com 
 {"version":"0.0.0","name":"beathletics","buildDate":"\"2022-02-25T15:11:37.753Z\"","VERSION":"63561c3","COMMITHASH":"63561c35cb8843034844a826f54489e7453cd039","BRANCH":"HEAD","LASTCOMMITDATETIME":"2022-02-25T16:07:22+01:00"}

**Comment by fwauters** [comment]
ok en dev
