### ISSUE TITLE
Commentaire de modification

### ISSUE THREAD

**Issue by robot-athletics** [betrailrun/beath-track#7]
Ajouter dans le titre "Expliquez la raison..." le nbre de caractères min.
 Report by Renauld JA renauld.chapellier@acdampicourt.be 
 {"version":"0.0.0","name":"beathletics","buildDate":"\"2022-03-18T14:05:46.511Z\"","VERSION":"5b4ecbc","COMMITHASH":"5b4ecbc3e7883e33de30df8492cb18ecd557590b","BRANCH":"uat","LASTCOMMITDATETIME":"2022-03-18T15:05:21+01:00"}

**Comment by fwauters** [comment]
ok en dev
