### ISSUE TITLE
Results format

### ISSUE THREAD

**Issue by robot-athletics** [betrailrun/beath-track#9]
Performance format in ce, ntimeter (high jump, long jump...) are incorrect.
2.00 is shown as 2, 2.10 is shown as 2.10
 Report by Renauld Chapellier renauld.chapellier@gmail.com 
 {"version":"0.0.0","name":"beathletics","buildDate":"\"2022-03-18T14:05:46.511Z\"","VERSION":"5b4ecbc","COMMITHASH":"5b4ecbc3e7883e33de30df8492cb18ecd557590b","BRANCH":"uat","LASTCOMMITDATETIME":"2022-03-18T15:05:21+01:00"}

**Comment by fwauters** [comment]
Réglé en dev
